# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 468)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 370, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(520, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(0, 290, 641, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(200, 0, 20, 301))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(420, 0, 20, 301))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(0, 70, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(0, 140, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(0, 220, 151, 16))
        self.label_6.setObjectName("label_6")
        self.ind_pobla1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.ind_pobla1.setGeometry(QtCore.QRect(0, 90, 66, 23))
        self.ind_pobla1.setObjectName("ind_pobla1")
        self.ind_propa1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.ind_propa1.setGeometry(QtCore.QRect(0, 160, 66, 23))
        self.ind_propa1.setObjectName("ind_propa1")
        self.Indi_viaje1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.Indi_viaje1.setGeometry(QtCore.QRect(0, 240, 66, 23))
        self.Indi_viaje1.setObjectName("Indi_viaje1")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(210, 70, 131, 16))
        self.label_7.setObjectName("label_7")
        self.ind_pobla2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.ind_pobla2.setGeometry(QtCore.QRect(210, 90, 66, 23))
        self.ind_pobla2.setObjectName("ind_pobla2")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(210, 140, 151, 16))
        self.label_8.setObjectName("label_8")
        self.ind_propa2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.ind_propa2.setGeometry(QtCore.QRect(210, 160, 66, 23))
        self.ind_propa2.setObjectName("ind_propa2")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(210, 220, 151, 16))
        self.label_9.setObjectName("label_9")
        self.Indi_viaje2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.Indi_viaje2.setGeometry(QtCore.QRect(210, 240, 66, 23))
        self.Indi_viaje2.setObjectName("Indi_viaje2")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(430, 70, 131, 16))
        self.label_10.setObjectName("label_10")
        self.ind_pobla3 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.ind_pobla3.setGeometry(QtCore.QRect(430, 90, 66, 23))
        self.ind_pobla3.setObjectName("ind_pobla3")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(430, 140, 151, 16))
        self.label_11.setObjectName("label_11")
        self.ind_propa3 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.ind_propa3.setGeometry(QtCore.QRect(430, 160, 66, 23))
        self.ind_propa3.setObjectName("ind_propa3")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(430, 220, 151, 16))
        self.label_12.setObjectName("label_12")
        self.Indi_viaje3 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.Indi_viaje3.setGeometry(QtCore.QRect(430, 240, 66, 23))
        self.Indi_viaje3.setObjectName("Indi_viaje3")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(370, 300, 59, 14))
        self.label_13.setObjectName("label_13")
        self.salidas = QtWidgets.QTextEdit(self.centralWidget)
        self.salidas.setGeometry(QtCore.QRect(370, 320, 241, 81))
        self.salidas.setObjectName("salidas")
        self.spinIte = QtWidgets.QSpinBox(self.centralWidget)
        self.spinIte.setGeometry(QtCore.QRect(100, 320, 71, 31))
        self.spinIte.setObjectName("spinIte")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(20, 320, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(50, 380, 41, 16))
        self.label_15.setObjectName("label_15")
        self.spinVista = QtWidgets.QSpinBox(self.centralWidget)
        self.spinVista.setGeometry(QtCore.QRect(100, 370, 71, 31))
        self.spinVista.setObjectName("spinVista")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(190, 320, 71, 16))
        self.label_16.setObjectName("label_16")
        self.spinMuerte = QtWidgets.QSpinBox(self.centralWidget)
        self.spinMuerte.setGeometry(QtCore.QRect(260, 312, 81, 31))
        self.spinMuerte.setObjectName("spinMuerte")
        #MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 645, 19))
        self.menuBar.setObjectName("menuBar")
        #MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        #MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        #MainWindow.setStatusBar(self.statusBar)

        self.spinIte.setSingleStep(500)
        self.spinVista.setSingleStep(10)

        self.spinIte.setMaximum(3000)
        self.spinVista.setMaximum(500)

        self.spinIte.setMinimum(500)
        self.spinVista.setMinimum(10)

        self.spinMuerte.setMaximum(3000)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de Epidemias"))
        self.pushButton.setText(_translate("MainWindow", "Lanzar"))
        self.label.setText(_translate("MainWindow", "Población 1"))
        self.label_2.setText(_translate("MainWindow", "Población 1"))
        self.label_3.setText(_translate("MainWindow", "Población 3"))
        self.label_4.setText(_translate("MainWindow", "Indice de Población :"))
        self.label_5.setText(_translate("MainWindow", "Indice de Propagación"))
        self.label_6.setText(_translate("MainWindow", "Indice de Viaje"))
        self.label_7.setText(_translate("MainWindow", "Indice de Población :"))
        self.label_8.setText(_translate("MainWindow", "Indice de Propagación"))
        self.label_9.setText(_translate("MainWindow", "Indice de Viaje"))
        self.label_10.setText(_translate("MainWindow", "Indice de Población :"))
        self.label_11.setText(_translate("MainWindow", "Indice de Propagación"))
        self.label_12.setText(_translate("MainWindow", "Indice de Viaje"))
        self.label_13.setText(_translate("MainWindow", "Estado:"))
        self.label_14.setText(_translate("MainWindow", "Iteraciones:"))
        self.label_15.setText(_translate("MainWindow", "Vistas:"))
        self.label_16.setText(_translate("MainWindow", "Mueren en:"))

